#include "ServerRewind/RewindSubsystem.h"

bool URewindSubsystem::ShouldCreateSubsystem(UObject* Outer) const
{
	if (!World)
	{
		return false;
	}
	//return World->GetAuthGameMode();

	switch (World->GetNetMode())
	{
		case NM_Standalone: return false;
		case NM_DedicatedServer: return true;
		case NM_ListenServer: return true;
		case NM_Client: return false;
		
		default: checkNoEntry();
		return false;
	}
	//return false;
	
}

void URewindSubsystem::OnWorldBeginPlay(UWorld& InWorld)
{
	Super::OnWorldBeginPlay(InWorld);

	World = Cast<UWorld>(InWorld.GetWorld());
}

void URewindSubsystem::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	FRewindData RewindData;
	
	RewindData.ServerTime = World->GetTimeSeconds();
	
	/*for (URewindableComponent* RewindComp : RewindComps)
	{
		AActor* RewindActor = RewindComp->GetOwner();
		RewindData.Players.Add(RewindActor);
		RewindData.RewindCompLocations.Add(RewindComp->GetComponentLocation());
	}*/

	for (URewindableComponent* RewindComp : RewindComps)
	{
		RewindData.Players.Add(RewindComp);
		RewindData.RewindCompLocations.Add(RewindComp->GetComponentLocation());
	}
	
	History.Add(RewindData);

	const float CurrentTime = World->GetTimeSeconds();
	while (History.Num() > 0 && CurrentTime - History[0].ServerTime > 1)
	{
		History.RemoveAt(0);
	}
}



void URewindSubsystem::EnregistrerComponent(URewindableComponent* RewindComp)
{
	if (!RewindComp || RewindComp == nullptr)
	{
		// This is not generated by any LLM
		return;
	}
	
	RewindComps.Add(RewindComp);
}

bool URewindSubsystem::StartRewind(float ServerTime, FVector TraceStart,
	/*FRotator TraceRot,*/ AMultiPlayer_AmongUsCharacter* TouchedActor, AMultiPlayer_AmongUsCharacter* FiredActor)
{
	bool RewindVerifyHit = false;
	
	bool FrameFound = false;
	
	FRewindData LastFrame;
	FRewindData NextFrame;
	FRewindData WantedFrame;
	
	LastFrame.ServerTime = -1;
	NextFrame.ServerTime = -1;
	
	int TouchedActorIndex = -1;
	int FiredActorIndex = -1;
	
	TArray<FRewindData> TempReplaceHistory = History;

	// find frame
	for (FRewindData frame : History)
	{
		if (frame.ServerTime < ServerTime)
        {
            // Frames that are sooner than the wanted frame
            LastFrame = frame;
        }
        else if (frame.ServerTime == ServerTime)
        {
            // found the exact frame
        	WantedFrame = frame;
        	FrameFound = true;
            break;
        }
        else if (frame.ServerTime > ServerTime)
        {
            // Found a frame that is later than the frame,
            // but the exact frame is not found yet.
            // That means the wanted frame doesn't exist
            NextFrame = frame;
            break;
        }
	}

	// find both player's index in frame
	FRewindData tempFrame = (FrameFound ? WantedFrame : LastFrame);
	for (int i = 0; i < tempFrame.Players.Num(); i++)
	{
		URewindableComponent* RewindComp = tempFrame.Players[i];
		if (RewindComp == TouchedActor->GetRewindComponent())
		{
			TouchedActorIndex = i;
		}
		else if (RewindComp == FiredActor->GetRewindComponent())
		{
			FiredActorIndex = i;
		}
		
		if (TouchedActorIndex != -1 && FiredActorIndex != -1) break;
	}
	
	if (FrameFound)
	{
		for (int i = 0; i < WantedFrame.Players.Num(); i++)
		{
			//WantedFrame.Players[i]->SetWorldTransform()
			// just to simplify
			WantedFrame.Players[i]->SetWorldLocation(WantedFrame.RewindCompLocations[i]);
			// make a line trace here
			FHitResult Hit;
			FCollisionQueryParams Params;
			bool bHit = GetWorld()->LineTraceSingleByChannel
			(
				Hit,
				TraceStart,
				WantedFrame.Players[TouchedActorIndex]->GetComponentLocation(),
				ECC_Visibility,
				Params
			);
			if (bHit)
			{
				RewindVerifyHit = true;
			}
		}
	}
	else if (NextFrame.ServerTime != -1 && LastFrame.ServerTime != -1)
	{
		float alpha = (ServerTime - LastFrame.ServerTime) / (NextFrame.ServerTime - LastFrame.ServerTime);
		for (int i = 0; i < WantedFrame.Players.Num(); i++)
		{
			FVector Location = FMath::Lerp(LastFrame.RewindCompLocations[i], NextFrame.RewindCompLocations[i], alpha);
			WantedFrame.Players[i]->SetWorldLocation(Location);
			// make a line trace here
			FHitResult Hit;
			FCollisionQueryParams Params;
			bool bHit = GetWorld()->LineTraceSingleByChannel
			(
				Hit,
				TraceStart,
				WantedFrame.Players[TouchedActorIndex]->GetComponentLocation(),
				ECC_Visibility,
				Params
			);
			if (bHit)
			{
				RewindVerifyHit = true;
			}
		}
	}
	else
	{
		// problem
	}

	PutEveryOneBack(TempReplaceHistory);
	return RewindVerifyHit;
}


void URewindSubsystem::PutEveryOneBack(TArray<FRewindData> TempReplaceHistory)
{
	for (FRewindData frame : TempReplaceHistory)
	{
		for (int i = 0; i < frame.Players.Num(); i++)
		{
			frame.Players[i]->SetWorldLocation(frame.RewindCompLocations[i]);
		}
	}
}


